### ISSUE TITLE
Issue when running plot_browser

### ISSUE THREAD

**Issue by mmahlke** [streetslab/dimelo#109]
I've received this error before and got around it by changing the name of my input file.bam
But that is not working this time
Why am I getting hit with a syntax error?

Command:
dm.plot_browser("/mypath/file.bam", "X", "assembly_hap1:79000000-79500000", "A", "/mypath/out/test", colorA='#cc322f', threshA=205, smooth=5000, dotsize=2, static=True)

Producing error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mypath/.conda/envs/dimelo/lib/python3.7/site-packages/dimelo/plot_browser.py", line 197, in plot_browser
    cores=num_cores,
  File "/mypath/.conda/envs/dimelo/lib/python3.7/site-packages/dimelo/parse_bam.py", line 284, in parse_bam
    make_db(fileName, sampleName, outDir)
  File "/mypath/.conda/envs/dimelo/lib/python3.7/site-packages/dimelo/parse_bam.py", line 154, in make_db
    create_sql_table(DATABASE_NAME, table_name, cols, dtypes)
  File "/mypath/.conda/envs/dimelo/lib/python3.7/site-packages/dimelo/utils.py", line 31, in create_sql_table
    c.execute("""DROP TABLE IF EXISTS """ + table_name + """;""")
sqlite3.OperationalError: near "-": syntax error

**Comment by mmahlke** [comment]
I thought I had resolved this as being a python issue, but has not been the case. 
Any advice?

**Comment by thekugelmeister** [comment]
Hi! To start, for full transparency, this version of the package is in the process of being deprecated in favor of a much more robust version. We hope to make that more publicly available soon. Part of the reason for this change is to help make debugging this sort of thing much easier, and to make it harder to trigger strange edge cases like this. 

That being said, I will do my best to help! Based on the (mostly unhelpful) error message and your comment about file naming, it does seem as if this might be a file name issue? Are there any hyphens in the name of your bam file? I'm not sure why that would break things but I'm starting with a small shot in the dark.

**Comment by mmahlke** [comment]
Hi! Thanks--I am aware of the newer version but haven't tested it. Is it fully functional now? I'm happy to switch over if I cannot resolve this issue.

Further, the naming convention for this file is no different than several other files I have run the same command with. It does not contain hyphens but does contain underscores (as do the other successfully run files).

One weird thing is that I think (not totally sure) that this error pops up after the command might fail for another reason (like wrong file path or something simple). So I'm wondering if there's an intermediate file getting dropped somewhere during analysis, and that is why the error is being returned on subsequent runs of the same bam file? But I haven't been able to find where a temp or intermediate file might go.

**Comment by mmahlke** [comment]
I figured it out. An errant '-' in the plot title! I guess plot title is a part of the table name. Thanks!
